from __future__ import annotations
from typing import Protocol

class MissionLogger(Protocol):
    def log_departure(self, record) -> None: ...
    def log_return(self, creature_name: str) -> None: ...

class MissionNotifier(Protocol):
    def notify(self, message: str) -> None: ...

class SortStrategy(Protocol):
    def sort(self, creatures: list) -> list: ...

class Command(Protocol):
    def execute(self) -> None: ...
    def undo(self) -> None: ...